### ISSUE TITLE
lndmon  shuts down after GetInfo

### ISSUE THREAD

**Issue by Fopstronaut** [lightninglabs/lndmon#109]
lndmon keeps crashing with this error:
```
Lndmon exiting with error: ChainCollector GetInfo failed with: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Stopping Prometheus Exporter
[INF] HTLC: Stopping Htlc Monitor
ChainCollector GetInfo failed with: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
LND version: 0.18.0-beta
lndmon version: 02ee7ca

**Comment by guggero** [comment]
`context deadline exceeded` means something is running into a timeout. Is your `lnd` responding quickly? Do you experience long response times as well if you run `lncli getinfo`?

**Comment by guggero** [comment]
So you see this consistently? Not just once in a while?
Can you post your lndmon config please?

**Comment by guggero** [comment]
It's very weird... Can you set an explicit value (e.g. `--lnd.rpctimeout=1m`) to make sure it's not a weird issue with 0 being used as the timeout?

**Comment by mrfelton** [comment]
We see this pretty frequently too and I also understand the issue to be from slow calls to GetInfo. We see it from time to tie even with the rpc timeout increased to `120s`.

Is it intentional that the service crashes when this happens? Seems like it could be better handled by logging an error message.

**Comment by guggero** [comment]
Very weird that the `GetInfo` call would sometimes take that long...

> Is it intentional that the service crashes when this happens?

I think the idea is to make sure `lndmon` doesn't just sit there when the connection to `lnd` fails or the certificate is expired. So shutting down means it will be restarted in a Docker/k8s/systemd environment and the connection re-attempted.
But I guess we could look at the error and not shut down on timeouts. I'll create a PR.

**Comment by mrfelton** [comment]
> I think the idea is to make sure lndmon doesn't just sit there when the connection to lnd fails or the certificate is expired.

Maybe use the `GetState` RPC to run that level of health check?

**Comment by guggero** [comment]
> Maybe use the GetState RPC to run that level of health check?

I added an error check in #110 for just the `GetInfo` call, since that seems to sometimes take longer. It's weird that we never see that problem in our environment...

What's your `lnd`'s database backend? `bbolt`? And have you turned on freelist sync?

**Comment by mrfelton** [comment]
> What's your lnd's database backend? bbolt? And have you turned on freelist sync?

Yes, bbolt. freelist sync is not on.

**Comment by guggero** [comment]
Ah, right. Because `GetInfo` does make one or more calls to `bitcoind` that can actually be the slowing factor. And it might actually hit the RPC connection limit on `bitcoind` if many other queries are going on at the same time, then needs to wait for a connection slot to free up.
So I think the approach of only allowing timeouts on the `GetInfo` call in the PR above is probably right. Then we'll still shut down if `lndmon` can't connect to `lnd` anymore.

**Comment by guggero** [comment]
@mrfelton and @Fopstronaut can you please try if #110 fixes your problem? Then I can merge that and push a new release out.
